SELECT LOPTINCHI.MAMH,MONHOC.TENMH,SINHVIEN.HO, SINHVIEN.TEN,LOP.TENLOP,KHOA.MAKHOA 
FROM (SELECT LOPTINCHI.MAMH, LOPTINCHI.MAKHOA FROM  LOPTINCHI) AS LOPTINCHI  
JOIN  (SELECT MONHOC.TENMH, MONHOC.MAMH FROM  MONHOC) AS MONHOC  ON LOPTINCHI.MAMH = MONHOC.MAMH  
JOIN  (SELECT KHOA.MAKHOA FROM KHOA) AS KHOA  ON LOPTINCHI.MAKHOA = KHOA.MAKHOA  
JOIN  (SELECT LOP.TENLOP, LOP.MAKHOA FROM  LOP WHERE LOP.TENLOP = N'D15CQCP01') AS LOP  ON LOP.MAKHOA = KHOA.MAKHOA  
JOIN  (SELECT SINHVIEN.HO, SINHVIEN.TEN, SINHVIEN.MALOP FROM  SINHVIEN) AS SINHVIEN  ON SINHVIEN.MALOP = LOP.MALOP

SELECT LOPTINCHI.MAMH,MONHOC.TENMH,SINHVIEN.HO, SINHVIEN.TEN,LOP.TENLOP,KHOA.TENKHOA 
FROM (SELECT LOPTINCHI.MAMH, LOPTINCHI.MAKHOA FROM  LOPTINCHI) AS LOPTINCHI  
JOIN  (SELECT MONHOC.TENMH, MONHOC.MAMH FROM  MONHOC) AS MONHOC  ON LOPTINCHI.MAMH = MONHOC.MAMH  
JOIN  (SELECT KHOA.TENKHOA, KHOA.MAKHOA FROM  KHOA) AS KHOA  ON LOPTINCHI.MAKHOA = KHOA.MAKHOA  
JOIN  (SELECT LOP.TENLOP, LOP.MAKHOA FROM  LOP) AS LOP  ON LOP.MAKHOA = KHOA.MAKHOA
JOIN  (SELECT SINHVIEN.HO, SINHVIEN.TEN, SINHVIEN.MALOP FROM  SINHVIEN) AS SINHVIEN  ON SINHVIEN.MALOP = LOP.MALOP

SELECT LOPTINCHI.MAMH,LOP.TENLOP,KHOA.TENKHOA,SINHVIEN.HO, SINHVIEN.TEN,MONHOC.TENMH 
FROM (SELECT LOPTINCHI.MAMH, LOPTINCHI.MAKHOA FROM  LOPTINCHI) AS LOPTINCHI 
 JOIN  (SELECT KHOA.TENKHOA, KHOA.MAKHOA FROM  KHOA) AS KHOA  ON LOPTINCHI.MAKHOA = KHOA.MAKHOA  
 JOIN  (SELECT MONHOC.TENMH, MONHOC.MAMH FROM  MONHOC) AS MONHOC  ON LOPTINCHI.MAMH = MONHOC.MAMH  
 JOIN  (SELECT LOP.TENLOP, LOP.MAKHOA FROM  LOP) AS LOP  ON LOP.MAKHOA = KHOA.MAKHOA 
  JOIN  (SELECT SINHVIEN.HO, SINHVIEN.TEN, SINHVIEN.MALOP FROM  SINHVIEN) AS SINHVIEN  ON SINHVIEN.MALOP = LOP.MALOP