SELECT SINHVIEN.HO, SINHVIEN.TEN, DANGKY.DIEM_CC, DANGKY.DIEM_GK, DANGKY.DIEM_CK, LOPTINCHI.HOCKY, MONHOC.TENMH 
FROM (SELECT DANGKY.DIEM_CC, DANGKY.DIEM_GK, DANGKY.DIEM_CK,DANGKY.MASV,DANGKY.MALTC FROM   DANGKY) AS DANGKY  
JOIN  (SELECT SINHVIEN.HO, SINHVIEN.TEN,SINHVIEN.MASV FROM  SINHVIEN) AS SINHVIEN  ON DANGKY.MASV = SINHVIEN.MASV  
JOIN  (SELECT LOPTINCHI.HOCKY,LOPTINCHI.MALTC FROM  LOPTINCHI) AS LOPTINCHI  ON DANGKY.MALTC = LOPTINCHI.MALTC 
JOIN  (SELECT MONHOC.TENMH,MONHOC.MAMH FROM  MONHOC) AS MONHOC  ON LOPTINCHI.MAMH = MONHOC.MAMH

SELECT SINHVIEN.HO, SINHVIEN.TEN, DANGKY.DIEM_CC, DANGKY.DIEM_GK, DANGKY.DIEM_CK, LOPTINCHI.HOCKY, MONHOC.TENMH 
FROM (SELECT DANGKY.DIEM_CC, DANGKY.DIEM_GK, DANGKY.DIEM_CK,DANGKY.MASV,DANGKY.MALTC FROM   DANGKY) AS DANGKY 
 JOIN  (SELECT SINHVIEN.HO, SINHVIEN.TEN,SINHVIEN.MASV FROM  SINHVIEN) AS SINHVIEN  ON DANGKY.MASV = SINHVIEN.MASV  
 JOIN  (SELECT LOPTINCHI.HOCKY,LOPTINCHI.MALTC,LOPTINCHI.MAMH FROM   LOPTINCHI) AS LOPTINCHI  ON DANGKY.MALTC = LOPTINCHI.MALTC  
 JOIN  (SELECT MONHOC.TENMH,MONHOC.MAMH FROM  MONHOC) AS MONHOC  ON LOPTINCHI.MAMH = MONHOC.MAMH